// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

export const metadata = {
  title: 'Randify App',
  description: 'Generated by Next.js',
  icon: 'https://p7.hiclipart.com/preview/663/591/824/5bbc0e1f32507.jpg',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <><head>
      <title>{metadata.title}</title>
      <link rel="icon" href={metadata.icon} />
    </head><html lang="en">
        <body>{children}</body>
      </html></>
  )
}